sudo: required

language: python

python:
  - "2.7"

before_script:
  - sudo apt-get install python-demjson
  - sudo apt-get install libxml2-utils
  - pip install html5lib

script: python ./tools/lint/lint.py -p
